### ISSUE TITLE
ModuleNotFoundError: No module named 'jinja2'

### ISSUE THREAD

**Issue by PlatinumLucario** [csukuangfj/PortAudioSharp2#10]
I don't think there's any guide on how to get jinja2 working properly in here. Because I've tried installing jinja2 via pip, and it still comes up with this error when I try to run generate.py:
```
Traceback (most recent call last):
  File "C:\Users\Silve\source\repos\Bassoon\src\Bassoon\scripts\generate.py", line 8, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'

```

And to confirm, yes I've disabled the python app installer in App execution aliases to make sure no other python installation is conflicting.
![image](https://github.com/csukuangfj/PortAudioSharp2/assets/1906189/c310c77f-d3ad-4da3-930e-dedc595367be)

Have you had this issue before? And does anyone here know how to fix this issue? Because I really don't know how to set it up properly.

**Comment by csukuangfj** [comment]
Could you show the screenshot about how you installed `jinja2`? I need to see the logs.

**Comment by PlatinumLucario** [comment]
Here's the screenshot:
![image](https://github.com/csukuangfj/PortAudioSharp2/assets/1906189/7aa701d3-f542-47b8-8c63-42391e5c3775)

**Comment by csukuangfj** [comment]
Please show the installation logs, not the logs about how you use it.

**Comment by PlatinumLucario** [comment]
I couldn't find any existing pip installation logs, but I did ``pip install jinja2 --log install.log`` to log the installation of jinja2.
[install.log](https://github.com/csukuangfj/PortAudioSharp2/files/14065744/install.log)

**Comment by PlatinumLucario** [comment]
Okay, so I found what I was doing wrong. It turns out that Python 3.12 was still set as the default for opening .py files (because I was originally using python 3.12 in other projects before changing the environment variables to use 3.10 instead), so I worked around that by including the python keyword to the command: ``python generate.py``. And the next issue I found, was that it was giving the following error:
````
FileNotFoundError: [Errno 2] No such file or directory: './macos/portaudio.runtime.csproj'
````
It turns out that the code in generate.py was missing these important pieces of code needed to create the directories:
```python
    os.makedirs('./macos', exist_ok=True)
```
```python
    os.makedirs('./linux', exist_ok=True)
```
```python
    os.makedirs('./windows', exist_ok=True)
```

This should also fix the main issue with the generate.py failing to create the [osname].runtime.csproj files
