### ISSUE TITLE
Microphone recording sample

### ISSUE THREAD

**Issue by Swimburger** [csukuangfj/PortAudioSharp2#11]
I'm looking for a cross-platform way of getting microphone input to my application.
Based on the README I assume this project can do this, but I don't know how.
Is there some documentation or sample of the main use cases this library solves, microphone input in praticular?

Thanks!

**Comment by csukuangfj** [comment]
there is a link to the sample in the readme

**Comment by Swimburger** [comment]
I missed that, thanks, I'll check it out!
