### ISSUE TITLE
Please reimplement generate.py in F# or C#.

### ISSUE THREAD

**Issue by daveyostcom** [csukuangfj/PortAudioSharp2#12]
You can package it as a `#!` file so it doesn’t have to be built to use it.  Python is a pain.  Thanks.

**Comment by csukuangfj** [comment]
Could you be more specific? Sorry that I cannot understand it.

**Comment by daveyostcom** [comment]
Please reimplement generate.py in F# or C# so we don't have to deal with python.

**Comment by csukuangfj** [comment]
generate.py is to publish the project as a nuget package.

As an end user, you don't need to deal with generate.py.

You only need to import the nuget package in your project.

**Comment by csukuangfj** [comment]
You can find the usage of this project in other project, such as the following one
https://github.com/k2-fsa/sherpa-onnx/blob/master/dotnet-examples/speech-recognition-from-microphone/speech-recognition-from-microphone.csproj

```
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="org.k2fsa.sherpa.onnx" Version="*" />
    <PackageReference Include="PortAudioSharp2" Version="*" />
  </ItemGroup>
```

All you need is to include the following line in your project. You don't need to run generate.py at all.
```
 <PackageReference Include="PortAudioSharp2" Version="*" />
```

**Comment by csukuangfj** [comment]
Please tell us why you need to run generate.py

**Comment by daveyostcom** [comment]
I added the PortAudioSharp2 project to my solution so I have it all there for debugging and can make changes.  Problem is, when I rebuild all, I get about 140 lines of this:
```
1>------- Started building project: PortAudioSharp
1>PortAudioSharp.csproj: Warning NU1801 : The local source '/Users/yost/p/dev/leo/dotnet/PortAudioSharp2/PortAudioSharp/packages' doesn't exist.
1>PortAudioSharp.csproj: Warning NU1801 : The local source '/Users/yost/p/dev/leo/dotnet/PortAudioSharp2/PortAudioSharp/packages' doesn't exist.
...
1>PortAudioSharp.csproj: Warning NU1801 : The local source '/Users/yost/p/dev/leo/dotnet/PortAudioSharp2/PortAudioSharp/packages' doesn't exist.
1>PortAudioSharp.csproj: Warning NU1801 : The local source '/Users/yost/p/dev/leo/dotnet/PortAudioSharp2/PortAudioSharp/packages' doesn't exist.
```

**Comment by csukuangfj** [comment]
This project is supposed to be used by adding the nuget package to your project.

If you want to include the whole project into your own, you should know how to modify it.
