### ISSUE TITLE
Add osx-arm64

### ISSUE THREAD

**Issue by SmartFoxServer** [csukuangfj/PortAudioSharp2#23]
When using portaudiosharp2 on macOS on newer Macs (arm-based), native library is not found because missing from dependancies.

**Comment by csukuangfj** [comment]
Sorry for the late reply.

Could you try version `1.0.2`? 

`osx-arm64` is supported now.

**Comment by SmartFoxServer** [comment]
Thank you for your help!
Updated and working as expected.
Having arm versions for the other operating system would be great too.

**Comment by csukuangfj** [comment]
> Having arm versions for the other operating system would be great too.

Would you mind helping test it once we have it?

**Comment by SmartFoxServer** [comment]
Sure. Our project, which uses your package, will be tested on those platforms too. Maybe it will take some time before we are ready to test.

**Comment by csukuangfj** [comment]
Closing via #25
