### ISSUE TITLE
Add iOS target

### ISSUE THREAD

**Issue by jona-1993** [csukuangfj/PortAudioSharp2#27]
Hello,

Can you add the iOS compatibility? [https://github.com/PortAudio/portaudio/pull/881](url)

I modified your project for make some tests.

It need to have:

public const string PortAudioDLL = "__Internal";

And not:

public const string PortAudioDLL = "portaudio";

Maybe you should add an iOS target and add an #if IOS directive...?

**Comment by csukuangfj** [comment]
Could you make a PR to this repo?

I don't have time to write code for this repo at the moment.

**Comment by jona-1993** [comment]
I replaced by __Internal at the moment. But I can try to make this correction. 
I will try to make a PR after. I've never done a PR before to be honest. ;)

**Comment by csukuangfj** [comment]
>  I've never done a PR before to be honest. ;)

Then it is time to learn how to do it .

**Comment by jona-1993** [comment]
The pull request is created.

**Comment by csukuangfj** [comment]
Closing via #28
