### ISSUE TITLE
Environment Requirements for linux portaudio?

### ISSUE THREAD

**Issue by Crash0v3r1de** [csukuangfj/PortAudioSharp2#32]
Working on testing if I can use this library in my project, compiled a console app that simply outputs the audio devices into the console but when ran on the machine (Debian 11) it throws libportaudio.so is not found.

I compiled and installed it from the github directly - https://github.com/PortAudio/portaudio
Still throwing that error, tried copying the .so and .a to project root on a gamble.

Is there something I'm missing on the Debian side to get it functional?

**Comment by csukuangfj** [comment]
could you describe how you are using this project?

**Comment by Crash0v3r1de** [comment]
> could you describe how you are using this project?

Super basic right now just to test if I can use it. Installed the PortAudioSharp2 via Nuget to my .net 8 console app, added this code to the main()
```
Console.WriteLine($"Number of devices: {PortAudio.DeviceCount}");
            for (int i = 0; i != PortAudio.DeviceCount; ++i)
            {
                Console.WriteLine($" Device {i}");
                DeviceInfo deviceInfo = PortAudio.GetDeviceInfo(i);
                Console.WriteLine($"   Name: {deviceInfo.name}");
                Console.WriteLine($"   Max input channels: {deviceInfo.maxInputChannels}");
                Console.WriteLine($"   Default sample rate: {deviceInfo.defaultSampleRate}");
            }
            int deviceIndex = PortAudio.DefaultInputDevice;
            if (deviceIndex == PortAudio.NoDevice)
            {
                Console.WriteLine("No default input device found");
            }
```

Copied it from one of the examples to test real quick. Compiled the project to a linux binary on WSL ubuntu 22, copied the publish folder to a Debian 11 VM with PortAudio compiled as per their docs. When ran the error "libportaudio.so is not found" is thrown.

**Comment by csukuangfj** [comment]
> Installed the PortAudioSharp2 via Nuget to my .net 8 console app

Could you describe in detail how you did that?

**Comment by Crash0v3r1de** [comment]
> > Installed the PortAudioSharp2 via Nuget to my .net 8 console app
> 
> Could you describe in detail how you did that?

via nuget manager in VS Studio 2022
![image](https://github.com/user-attachments/assets/90741d7d-81bd-4d0c-b270-fe4bb7df4b25)
![image](https://github.com/user-attachments/assets/0d5d9048-9eb0-4350-8214-bca8d7aefb1c)

**Comment by csukuangfj** [comment]
Is your cpu x64 or arm64?

**Comment by Crash0v3r1de** [comment]
> Is your cpu x64 or arm64?

x64, compiled with
`dotnet publish -r linux-x64 -c Release`
on WSL Ubuntu 22

**Comment by csukuangfj** [comment]
which version of portaudiosherpa2 are you using?

you can find the latest version here
https://www.nuget.org/packages/PortAudioSharp2

**Comment by Crash0v3r1de** [comment]
> which version of portaudiosherpa2 are you using?
> 
> you can find the latest version here https://www.nuget.org/packages/PortAudioSharp2

1.0.4, I see on that nuget link it's only showing .NET 6 though - which could be the issue? I'm on .NET 8.

**Comment by Crash0v3r1de** [comment]
Okay cool, after some fiddling around libjack-dev libjack0 libjack-jackd2-0 are all needed to be installed. I did not add libjack-jackd2-0 until now.

**Comment by csukuangfj** [comment]
So does it work for you now?

**Comment by Crash0v3r1de** [comment]
> So does it work for you now?

Yup! just had to add those missing libraries/runtime and it's good to go! Thanks for this project, super helpful!
