### ISSUE TITLE
No Documentation for Streaming to Device

### ISSUE THREAD

**Issue by paulresdat** [csukuangfj/PortAudioSharp2#4]
I thought about leaving a comment on NAudio, but instead I've opened up an issue for further discussion.

The wrapper worked well with recognizing my device on a mac system, I was able to see my external sound card.  However there's missing documentation on how to send it streamed audio data from aiff files or ogg files, or any other kind of audio format.

In response to your comment on NAudio:

@csukuangfj yeah, it's a wrapper for streaming so I do think you can, but there's no documentation around that and certainly no documentation around utilizing with NAudio if it's possible.  I'd like to see this turn into something though because the API that exposes the devices is actually pretty simple and the nuget package itself is a quick easy install and X compatible which is great. If there was some abstraction around audio processing before it hits the device though, that would make this solution viable for someone like me.  I was able to view my external sound card device using it and querying open devices.  How do I send a WAV file though?  What do I need to do to send a .aiff file?  Let's start a discussion on what that would take.

**Comment by csukuangfj** [comment]
PortAudioSharp or PortAudioSharp2 is a simple wrapper around portaudio. All documentation can be found in portaudio.

If you have used the C API of portaudio, you will find that the recording example using PortAudioSharp2 is quite similar to its C counterpart.

**Comment by csukuangfj** [comment]
Also, the wrapper code is well documented. I suggest that you look at the code to find out its usage.

**Comment by csukuangfj** [comment]
We have an example for playing at https://github.com/k2-fsa/sherpa-onnx/tree/master/dotnet-examples/offline-tts-play

You can refer to the above example to send audio files to a speaker.
