### ISSUE TITLE
Is it possible to add Read/Write IO methods?

### ISSUE THREAD

**Issue by a6754z** [csukuangfj/PortAudioSharp2#7]
No API wrappers for  Read/Write IO methods: Pa_ReadStream, Pa_WriteStream. Is it possible to add them?

**Comment by csukuangfj** [comment]
This repo is copied from https://gitlab.com/define-private-public/Bassoon/-/tree/develop/src/Bassoon/PortAudioSharp

The sole contribution from us is to add pre-compiled portaudio libraries in the nuget package.

Please ask
https://gitlab.com/define-private-public/Bassoon/-/tree/develop/src/Bassoon/PortAudioSharp
to require new features.
