### ISSUE TITLE
No sound played out with output callback

### ISSUE THREAD

**Issue by a6754z** [csukuangfj/PortAudioSharp2#8]
I used PortAudioSharp2 for audio capturing and playing. Capturing works fine but playing does not work. No sound is played. While if I save the data as a WAV file, it can be played. Below are my part of codes.

//Initialization
int deviceIndex = PortAudio.DefaultOutputDevice;
if (deviceIndex == PortAudio.NoDevice)
{
    log.Error("No default output audio device found!!!");
    return;
}
DeviceInfo info = PortAudio.GetDeviceInfo(deviceIndex);
log.Debug($"Use default audio output device {deviceIndex} ({info.name})");
StreamParameters param = new StreamParameters();
param.device = deviceIndex;
param.channelCount = 1;
param.sampleFormat = SampleFormat.Float32;
param.suggestedLatency = (double)(Consts.SoundOutLatency / 1000.0);    //Consts.SoundOutLatency=100
param.hostApiSpecificStreamInfo = IntPtr.Zero;

var bufferSize = amrWbMixer.WaveFormat.AverageBytesPerSecond * 100 / 1000;   //6400
//var bufferSize = Consts.DefWaveFormat.ConvertLatencyToByteSize(Consts.SoundOutLatency);
portAudioOutCallback = new PortAudioSharp.Stream.Callback(PortAudioOutCallback);
PortAudioOutStream = new PortAudioSharp.Stream(inParams: null, outParams: param, sampleRate: Consts.AMRWB_PCM_SAMPLE_RATE,
    framesPerBuffer: (uint)bufferSize / 4, 
    streamFlags: StreamFlags.ClipOff,
    callback: portAudioOutCallback,
    userData: IntPtr.Zero);

//Callback
private StreamCallbackResult PortAudioOutCallback(nint input, nint output, uint frameCount, ref StreamCallbackTimeInfo timeInfo, StreamCallbackFlags statusFlags, nint userDataPtr)
{
    float[] buf = new float[frameCount];
    amrWbMixer.Read(buf, 0, (int)frameCount);    //Get the audio data.
    Marshal.Copy(buf, 0, output, (int)frameCount);
    return StreamCallbackResult.Continue;
}

//Stream start
if (!PortAudioOutStream.IsActive)
{
    PortAudioOutStream.Start();
}

**Comment by csukuangfj** [comment]
```
param.channelCount = 1;
param.sampleFormat = SampleFormat.Float32;

PortAudioOutStream = new PortAudioSharp.Stream(inParams: null, outParams: param, sampleRate: Consts.AMRWB_PCM_SAMPLE_RATE,
```

Do your samples match the above settings?

**Comment by a6754z** [comment]
> ```
> param.channelCount = 1;
> param.sampleFormat = SampleFormat.Float32;
> 
> PortAudioOutStream = new PortAudioSharp.Stream(inParams: null, outParams: param, sampleRate: Consts.AMRWB_PCM_SAMPLE_RATE,
> ```
> 
> Do you samples match the above settings?

Yes, the sample rate is 16000.
To verify it, I saved the raw data into a binary file in the callback function. I can play it using CoolEdit with the following settings.
![image](https://github.com/csukuangfj/PortAudioSharp2/assets/28583653/42ef654d-73e0-473a-b4d0-efae2d7ad965)

**Comment by csukuangfj** [comment]
We have a play example now with this repo. Please refer to
https://github.com/k2-fsa/sherpa-onnx/tree/master/dotnet-examples/offline-tts-play
