### ISSUE TITLE
macOS  Error

### ISSUE THREAD

**Issue by DaZhiAmbit** [csukuangfj/PortAudioSharp2#9]
System.DllNotFoundException: Unable to load shared library 'portaudio' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libportaudio, 0x0001): tried: 'libportaudio' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibportaudio' (no such file), '/usr/lib/libportaudio' (no such file, not in dyld cache), 'libportaudio' (no such file), '/usr/local/lib/libportaudio' (no such file), '/usr/lib/libportaudio' (no such file, not in dyld cache)

**Comment by csukuangfj** [comment]
Could you describe what you have done to produce the above error?

**Comment by csukuangfj** [comment]
No response. Closing.
